### ISSUE TITLE
Suggestion: Handle data length reductions

### ISSUE THREAD

**Issue by scoman81** [dennyferra/TypeWatch#16]
There are two common cases (actually two derivatives of the same case, that just feel different) that would be nice to see handled by this plugin:

1. Full erase. Type some data, Shift+Home, Backspace. This case is when you've typed and then erased everything. The callback doesn't fire, and thus you can't restore state. (I'm using this to trigger a filter on a table of data, and a full erase should restore all data).

2. with captureLength set to 3, type 3 chars, let event fire, then backspace. This case should also be able to let the user restore default state, since 2 characters are considered the same as no characters, but the callback won't fire because the input has only 2 characters.

These are really both the same case: when the data length decreases from over the captureLength setting, to under the captureLength setting.

**Comment by szepeviktor** [comment]
This line makes the empty state work.
```php
|| (value.length === 0 && timer.text.length > 0)
```
