### ISSUE TITLE
does not fire event if new input equal saved input

### ISSUE THREAD

**Issue by mtz** [dennyferra/TypeWatch#24]
hi,

if i write an string into input field, delete the string and type the same string again, typewatch is not firing the callback event. 

is this an bug or an feature? 
can you make that as config variable?

if this is an feature, can you explain why u do that?

thanks
mtz

**Comment by Unisolve** [comment]
I have just stumbled on a similar problem on a site where we are using typewatch. If a user makes an entry in a text field that is greater than options.captureLength then my callback is executed.

However, if the user simply changes the case of the data they entered, the callback is never executed. I can see why this is happening, (the plugin folds everything to uppercase before it does it's comparison), however, I would love to be able to override this behavior.
