### ISSUE TITLE
publish on NPM

### ISSUE THREAD

**Issue by davidosomething** [dennyferra/TypeWatch#25]
v.2.2.0 is in bower but not on NPM (someone else seems to have forked and created the unofficial NPM module and still has "official" in the readme)

https://www.npmjs.com/package/jquery.typewatch

Can you publish this one?

**Comment by skevy** [comment]
@dennyferra wow, I'm so sorry I name-squatted on this package! This was so long ago -- before using npm for all JS packages was a thing.

Can I transfer the ownership of this to you?

**Comment by dennyferra** [comment]
@skevy Hey no worries, I've been a bit busy lately and nearly forgot about this! My npm user is: dennyferra

Thanks!

**Comment by skevy** [comment]
Ok added you as an owner! Feel free to publish whenever. Sorry again! Thanks for the great project that I used 4 years ago! :-p

**Comment by ThiefMaster** [comment]
It would be nice if the latest versions were on npm as well.

**Comment by dennyferra** [comment]
Latest version has been published to npm, thanks!
