### ISSUE TITLE
Check license

### ISSUE THREAD

**Issue by pvnr0082t** [dennyferra/TypeWatch#28]
Hi @dennyferra ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this library on cdnjs.
The comment in [jquery.typewatch.js](https://github.com/dennyferra/TypeWatch/blob/master/jquery.typewatch.js) show that under dual licenses. Could you please help me check which version of GPL license you use? or point out from [license-list.json](https://github.com/cdnjs/cdnjs/blob/master/tools/license-list.json). Thanks.

https://github.com/cdnjs/cdnjs/pull/8022
https://github.com/cdnjs/cdnjs/issues/7848

**Comment by pvnr0082t** [comment]
Sorry for bother you. I think http://www.gnu.org/licenses/gpl.html is GPL-3.0. Maybe you can help me double check it.

**Comment by dennyferra** [comment]
@pvnr0082t Not a problem, and yes confirmed the license is GPL v3

**Comment by pvnr0082t** [comment]
@dennyferra Thanks for your Help. :+1:
