### ISSUE TITLE
Destroy typewatch?

### ISSUE THREAD

**Issue by drosanda** [dennyferra/TypeWatch#36]
Hi There, 

Short story I'm currently implement type watch input text on a boostrap modal. This modal has two trigger button, if I execute any button, typewatch only work on the first button that I was execute. I dont know exaclty whats going on. So, I decided want to try destroying typeWatch first and then revoke while modal shown.

Anyone can tell me how to destroy typewatch? 

thanks

**Comment by winzig** [comment]
I just came here to find out the same thing, looked through the code and this is where your given elements get bound to something:

https://github.com/dennyferra/TypeWatch/blob/87b9f18ed9bbc8ee6b07e2b6336f373a9ddb25eb/jquery.typewatch.js#L93

So you should be able to destroy typeWatch by calling the jQuery `.off()` method for those same events on your elements:

```js
jQuery(".your-elements").off("keydown paste cut input");
```
